version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: tj-api-example
        container_name: api-example-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        environment:
            DB_PASSWORD: cImzf6aodMMulOxlP7WEbCO7DjuD2T8e
        networks:
            - api-example-network
    db:
        image: mysql:8.0
        container_name: api-example-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: cImzf6aodMMulOxlP7WEbCO7DjuD2T8e
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - api-example-network
    nginx:
        image: nginx:1.23-alpine
        container_name: api-example-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - api-example-network

networks:
    api-example-network:
        driver: bridge
